-- MySQL Script generated by MySQL Workbench
-- Mon Apr  5 10:28:09 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema retail_test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema retail_test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `retail_test` DEFAULT CHARACTER SET utf8 ;
USE `retail_test` ;

-- -----------------------------------------------------
-- Table `retail_test`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `retail_test`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `gov_id` INT NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `company` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `gov_id_UNIQUE` (`gov_id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `retail_test`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `retail_test`.`orders` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `total` FLOAT NOT NULL DEFAULT '0',
  `subtotal` FLOAT NOT NULL DEFAULT '0',
  `taxes` FLOAT NOT NULL DEFAULT '0',
  `paid` TINYINT NULL DEFAULT '0',
  `user_id` INT NOT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `retail_test`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `retail_test`.`payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `retail_test`.`payments` (
  `payment_id` INT NOT NULL AUTO_INCREMENT,
  `type` ENUM('PAYPAL', 'CREDIT CARD') NOT NULL,
  `date` DATE NOT NULL,
  `txn_id` INT NOT NULL,
  `total` FLOAT NOT NULL,
  `status` ENUM('PENDING', 'PAID') NOT NULL,
  `order_id` INT NOT NULL,
  PRIMARY KEY (`payment_id`),
  INDEX `fk_payments_orders1_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_payments_orders1`
    FOREIGN KEY (`order_id`)
    REFERENCES `retail_test`.`orders` (`order_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `retail_test`.`shippings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `retail_test`.`shippings` (
  `ship_id` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(120) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `country` VARCHAR(60) NOT NULL,
  `cost` FLOAT NOT NULL,
  `order_id` INT NOT NULL,
  PRIMARY KEY (`ship_id`),
  INDEX `fk_shippings_orders1_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_shippings_orders1`
    FOREIGN KEY (`order_id`)
    REFERENCES `retail_test`.`orders` (`order_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
